version: '3'

services:
    app:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile.dev
        command: yarn start
        volumes:
            - ..:/app
        environment:
            NODE_ENV: ${NODE_ENV}
            APP_PORT: ${APP_PORT}
            APP_HOST: ${APP_HOST}
            APP_TITLE: ${APP_TITLE}
            APP_DESC: ${APP_DESC}
            CONTENTFUL_SPACE_ID: ${CONTENTFUL_SPACE_ID}
            CONTENTFUL_ACCESS_TOKEN: ${CONTENTFUL_ACCESS_TOKEN}
            CONTENTFUL_DELIVERY_TOKEN: ${CONTENTFUL_DELIVERY_TOKEN}
            CONTENTFUL_HOST: ${CONTENTFUL_HOST}
            CONTENTFUL_PREVIEW_ACCESS_TOKEN: ${CONTENTFUL_PREVIEW_ACCESS_TOKEN}
        ports:
            - ${APP_PORT}:${APP_PORT}
