version: '3'

services:
    app:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        command: yarn all
        volumes:
            - ..:/app
        ports:
            - ${APP_PORT}:${APP_PORT}
            - ${DATA_FRONTEND_PORT}:${DATA_FRONTEND_PORT}
            - ${DATA_BACKEND_PORT}:${DATA_BACKEND_PORT}
        environment:
            APP_PORT: ${APP_PORT}
            REACT_APP_TITLE: ${APP_TITLE}
            REACT_APP_DESC: ${APP_DESC}
            REACT_APP_ENV: ${DATA_BACKEND_ENV}
            REACT_APP_PORT: ${DATA_BACKEND_PORT}
            REACT_APP_DATA_LOCATION: ${APP_DATA_LOCATION}
            FAST_REFRESH: ${FAST_REFRESH}
            CHOKIDAR_USEPOLLING: ${CHOKIDAR_USEPOLLING}
            DATA_FRONTEND_PORT: ${DATA_FRONTEND_PORT}
            DATA_BACKEND_HOST: ${DATA_BACKEND_HOST}
            DATA_BACKEND_PORT: ${DATA_BACKEND_PORT}
            DATA_BACKEND_CONSOLE_LOG: ${DATA_BACKEND_CONSOLE_LOG}
            DATA_BACKEND_ENV: ${DATA_BACKEND_ENV}
            DATA_BACKEND_NAME: ${APP_TITLE}
            DATA_BACKEND_DESC: ${APP_DESC}
            DB_TYPE: ${DB_TYPE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATA: ${DB_DATA}
            GITHUB_EMAIL: ${GITHUB_EMAIL}
            GITHUB_USERNAME: ${GITHUB_USERNAME}
            GITHUB_TOKEN: ${GITHUB_TOKEN}
        depends_on:
            - mongodb
    mongodb:
        image: mongo
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - db_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
volumes:
    db_data:
