version: '3'

services:
    app:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        command: yarn start
        volumes:
            - ..:/app
        ports:
            - ${PORT}:3000
        environment:
            GITHUB_EMAIL: ${GITHUB_EMAIL}
            GITHUB_USERNAME: ${GITHUB_USERNAME}
            GITHUB_TOKEN: ${GITHUB_TOKEN}
    data-backend:
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.backend
        command: yarn start
        volumes:
            - ../data:/app
        ports:
            - ${DATA_BACKEND_PORT}:${DATA_BACKEND_PORT}
        depends_on:
            - mongodb
    mongodb:
        image: mongo
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - db_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    data-frontend:
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.frontend
        command: yarn start
        volumes:
            - ../data/frontend:/app
        ports:
            - ${DATA_FRONTEND_PORT}:3000
volumes:
    db_data:
