version: '3'

services:
    app:
        build:
            context: ../
            dockerfile: ./docker/dev.dockerfile
        command: yarn develop
        volumes:
            - ..:/app
            - node_modules:/app/node_modules
        environment:
            DOCKER_BUILDKIT: ${DOCKER_BUILDKIT}
            NODE_ENV: ${NODE_ENV}
            APP_PORT: ${APP_PORT}
            APP_HOST: ${APP_HOST}
            INTERNAL_STATUS_PORT: ${INTERNAL_STATUS_PORT}
            GATSBY_WEBPACK_PUBLICPATH: ${GATSBY_WEBPACK_PUBLICPATH}
            GATSBY_GRAPHQL_IDE: ${GATSBY_GRAPHQL_IDE}
            GATSBY_TELEMETRY_DISABLED: ${GATSBY_TELEMETRY_DISABLED}
            PARCEL_WORKERS: ${PARCEL_WORKERS}
            APP_TITLE: ${APP_TITLE}
            APP_DESC: ${APP_DESC}
            CONTENTFUL_SPACE_ID: ${CONTENTFUL_SPACE_ID}
            CONTENTFUL_ACCESS_TOKEN: ${CONTENTFUL_ACCESS_TOKEN}
            GITHUB_REPO: ${GITHUB_REPO}
            GITHUB_EMAIL: ${GITHUB_EMAIL}
            GITHUB_USERNAME: ${GITHUB_USERNAME}
            GITHUB_TOKEN: ${GITHUB_TOKEN}
            SHARP_IGNORE_GLOBAL_LIBVIPS: ${SHARP_IGNORE_GLOBAL_LIBVIPS}
            CHOKIDAR_USEPOLLING: ${CHOKIDAR_USEPOLLING}
            FAST_REFRESH: ${FAST_REFRESH}
            npm_config_arch: ${npm_config_arch}
            npm_config_platform: ${npm_config_platform}

        ports:
            - ${APP_PORT}:${APP_PORT}
            - ${INTERNAL_STATUS_PORT}:${INTERNAL_STATUS_PORT}
volumes:
    node_modules:
