FROM node:14-alpine

RUN apk add \
    vips-dev \
    fftw-dev \
    build-base \
    python3 \
    git \
    ssh-client \
    --update --no-cache \
    --repository https://alpine.global.ssl.fastly.net/alpine/edge/testing/ \
    --repository https://alpine.global.ssl.fastly.net/alpine/edge/main

RUN yarn global add gatsby-cli gh-pages
RUN echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf

WORKDIR /app
