FROM node:14-alpine

WORKDIR /

# Install app dependencies
COPY ./data/package.json /
COPY ./data/yarn.lock /
COPY .env .

# setup node environment
ENV NODE_PATH=/node_modules
ENV PATH=$PATH:$NODE_PATH/.bin

# install packages
RUN yarn

# Create app directory
WORKDIR /app
