version: '3'

services:
    app:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile.dev
        command: yarn start
        volumes:
            - ..:/app
        environment:
            NODE_ENV: ${NODE_ENV}
            APP_PORT: ${APP_PORT}
            APP_HOST: ${APP_HOST}
            INTERNAL_STATUS_PORT: ${INTERNAL_STATUS_PORT}
            GATSBY_WEBPACK_PUBLICPATH: ${GATSBY_WEBPACK_PUBLICPATH}
            GATSBY_GRAPHQL_IDE: ${GATSBY_GRAPHQL_IDE}
            APP_TITLE: ${APP_TITLE}
            APP_DESC: ${APP_DESC}
            CONTENTFUL_SPACE_ID: ${CONTENTFUL_SPACE_ID}
            CONTENTFUL_ACCESS_TOKEN: ${CONTENTFUL_ACCESS_TOKEN}
            GITHUB_REPO: ${GITHUB_REPO}
            GITHUB_EMAIL: ${GITHUB_EMAIL}
            GITHUB_USERNAME: ${GITHUB_USERNAME}
            GITHUB_TOKEN: ${GITHUB_TOKEN}
            PARCEL_WORKERS: ${PARCEL_WORKERS}
        ports:
            - ${APP_PORT}:${APP_PORT}
            - ${INTERNAL_STATUS_PORT}:${INTERNAL_STATUS_PORT}
