name: Build on Contentful Publish Event

on:
  repository_dispatch:
    types: [publish-event]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
    steps:
      - name: Check out code into the directory
        uses: actions/checkout@v3.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '14.x'

      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v2.3.0

      - name: Cache
        uses: actions/cache@v3.0.2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn deploy

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: public
          cname: app.contentful.com
