name: Build Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [publish-event]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      APP_TITLE: ${{ secrets.APP_TITLE }}
      APP_DESC: ${{ secrets.APP_DESC }}
      GATSBY_WEBPACK_PUBLICPATH: ${{ secrets.GATSBY_WEBPACK_PUBLICPATH }}
    steps:
      - name: Check out code into the directory
        uses: actions/checkout@v4
      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v4

      - run: yarn predeploy

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: public
          cname: ${{ secrets.SITE_DOMAIN }}
          enable_jekyll: true
